---
# Title: OSSEC Agent
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# file: tasks/agents/ossec-agent-ubuntu-2204.yml
#
# Description:
#   This taskfile install the OSSEC
#   agent on this system.
#
- name: "Add APT packages requirements"
  ansible.builtin.apt:
    pkg:
    - build-essential
    - zlib1g-dev
    - libpcre2-dev
    - libevent-dev
    - libssl-dev
    state: present

- name: "Remove existing installation folders when exists"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /opt/ossec-agent-install
    - /tmp/pcre2
    
- name: "Download latest source of OSSEC"
  ansible.builtin.git:
    repo: 'https://github.com/ossec/ossec-hids.git'
    dest: /opt/ossec-agent-install

- name: "Download latest source of PCRE2 support"
  ansible.builtin.git:
    repo: 'https://github.com/PCRE2Project/pcre2.git'
    dest: /tmp/pcre2

- name: Move pcre2 to /opt/ossec-install/
  command: mv /tmp/pcre2 /opt/ossec-agent-install/src/external/

- name: "Transfer configuration files to client"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: server/preloaded-vars.conf.j2, dest: '/opt/ossec-install/etc/preloaded-vars.conf', desc: 'unattended source installation ' }
    - { src: server/ossec-control.service.j2, dest: '/etc/systemd/system/ossec-control.service', desc: 'systemd service' }

- name: "Install or upgrade ossec server"
  ansible.builtin.shell: cd /opt/ossec-agent-install/ ; PCRE2_SYSTEM=yes ./install.sh
  
  
  
