---
# Title: OSSEC Agent
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# file: tasks/agents/ossec-agent-ubuntu-2204.yml
#
# Description:
#   This taskfile install the OSSEC
#   agent on this system.
#
- name: "Add APT packages requirements"
  ansible.builtin.apt:
    pkg:
    - build-essential
    - zlib1g-dev
    - libpcre2-dev
    - libevent-dev
    - libssl-dev
    state: present

- name: "Remove existing installation folders when exists"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /opt/ossec-agent-install
    - /tmp/pcre2
    
- name: "Download latest source of OSSEC"
  ansible.builtin.git:
    repo: 'https://github.com/ossec/ossec-hids.git'
    dest: /opt/ossec-agent-install

- name: "Download latest source of PCRE2 support"
  ansible.builtin.git:
    repo: 'https://github.com/PCRE2Project/pcre2.git'
    dest: /tmp/pcre2

- name: "Move pcre2 to /opt/ossec-agent-install"
  command: mv /tmp/pcre2 /opt/ossec-agent-install/src/external/

- name: "Transfer configuration files to client"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'agent/preloaded-vars.conf.j2', dest: '/opt/ossec-agent-install/etc/preloaded-vars.conf', desc: 'unattended source installation ' }
    #- { src: server/ossec-control.service.j2, dest: '/etc/systemd/system/ossec-control.service', desc: 'systemd service' }

- name: "Install or upgrade ossec agent"
  ansible.builtin.shell: cd /opt/ossec-agent-install/ ; PCRE2_SYSTEM=yes ./install.sh
  
- name: "Add setting for repeating offenders Active Response section (/var/ossec/etc/ossec.conf) (WIP)"
  ansible.builtin.blockinfile:
    path: /var/ossec-agent/etc/ossec.conf
    marker: "    <!-- {mark} ANSIBLE MANAGED BLOCK - Repeated offenders -->"
    insertafter: "<!-- Active Response Config -->"
    block: |2
          <command>
             <name>firewall-drop</name>
             <executable>firewall-drop.sh</executable>
             <expect>srcip</expect>
             <timeout_allowed>yes</timeout_allowed>
          </command>

          <!-- Active Response Config -->
          <active-response>
            <!-- Specify a comma seperated list of timeouts per
               - re-incidence (in minutes).
              -->
            <repeated_offenders>30,60,120,240,480</repeated_offenders>
          </active-response>

         <active-response>
           <!-- Firewall Drop response. Block the IP for
              - 600 seconds on the firewall (iptables,
              - ipfilter, etc).
              -->
           <disabled>no</disabled>
           <command>firewall-drop</command>
           <agent_id>{{ ossec_agent_id }}</agent_id>
           <location>local</location>
           <rules_id></rules_id>
           <level>6</level>
           <timeout>600</timeout>
         </active-response>
  
