---
# Title: OSSEC Server
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/01-mysql-server.yml
#
# Description:
#   OSSEC server
# 
# Source(s):
#   - https://dev.mysql.com/doc/mysql-installation-excerpt/8.0/en/docker-mysql-getting-started.html
#   - https://hub.docker.com/_/mysql
#  
- name: "Install APT packages"
  ansible.builtin.apt:
    pkg:
    - docker.io
    - python3-docker

- name: "Pull Docker image MySQL Server"
  docker_image:
    name:  mysql/mysql-server:latest
    source: pull

- name: "Start docker MySQL database server"
  docker_container:
    name: guacamoledb
    image: mysql/mysql-server
    state: started
    restart: yes
    restart_policy: always
    ports:
      - "3306:3306"
    volumes:
      -  /opt/docker/guacamole/mysql/:/docker-entrypoint-initdb.d
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_administrative_password }}"
      MYSQL_DATABASE: "ossec"
      MYSQL_USER: "ossec"
      MYSQL_PASSWORD: "{{ mysql_database_pass }}"
