---
#
# https://grafana.com/grafana/download?edition=oss&platform=docker

- name: "Install APT packages"
  ansible.builtin.apt:
    pkg:
    - docker.io
    - python3-docker
    
- name: "Pull Grafana Docker image"
  docker_image:
    name: grafana/grafana-oss:latest
    source: pull

- name: "Create directory for Grafana entrypoint(s)"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/docker/grafana/var/lib/grafana
    - /opt/docker/grafana/etc/grafana
    - /opt/docker/grafana/var/log/grafana
    
    
- name: "Create Grafana container"
  docker_container:
    name: grafana
    image: grafana/grafana-oss
    state: started
    restart: yes
    restart_policy: always
    ports:
      - "3000:3000"
    #container_default_behavior: no_defaults
    volumes:
    #  - /opt/docker/grafana/data:/var/lib/grafana
    #  - /opt/docker/grafana/var/lib/grafana:/var/lib/grafana
    #  - /opt/docker/grafana/etc/grafana:/etc/grafana
    #  - /opt/docker/grafana/var/log/grafana:/var/log/grafana 
      - grafana-storage:/var/lib/grafana
    env:
      GF_SECURITY_ADMIN_USER: "{{ grafana_admin_user }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_pass }}"
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource


