---
# Title: OSSEC server
#
# Author: Bitfinity / L. Rutten 
# Owner: Bitfinity / L. Rutten
#
# File: tasks/server/ubt2204-amd64.yml
#
# Description:
#   This taskfile contains te tasks
#   for installing a OSSEC server.
#
- name: "Add APT packages requirements"
  ansible.builtin.apt:
    pkg:
    - build-essential
    - make
    - zlib1g-dev
    - libpcre2-dev
    - libevent-dev
    - libssl-dev
    - libsystemd-dev
    # -- for database support --
    #- mysql-dev
    #- postgresql-dev
    #- libsqlite3-dev
    state: present

- name: "Transfer unattended source installation file to client"
   ansible.builtin.template:
    src: server/preloaded-vars.conf.j2
    dest: etc/preloaded-vars.conf


